name: Test

on: [push]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v6.0.0

        - name: ls
          uses: ./.github/actions/my-action
          with:
            message: "Ruben"
