name: "My Action"
description: "An example GitHub Action"

inputs:
  message: 
    description: "The message to print"
    required: true
    default: "Hola"


runs:
  using: "composite"


  steps:
    - name: "Print Hello World"
      run: echo "Hola ${{ inputs.message }}"
      shell: bash